const fs = require('node:fs');
const path = require('node:path');
const { BMAD_HANDOFF_PACKETS } = require('./constants');
const { resolveUnderRoot } = require('./paths');
const { sha256 } = require('./store-postgres');
const { stringifyReviewPacket } = require('./toml');
const { validateDraft } = require('./validate');

async function exportBmadArtifacts({ config, store, slug }) {
  await validateDraft({ config, store, slug, reconcile: true });
  const runId = await store.createRun(`capability-forge export-bmad ${slug}`);
  try {
    const graph = await store.getPackGraph(slug);
    const outputRoot = `.capability-forge/drafts/${slug}`;
    const files = {
      [`${outputRoot}/SKILL.md`]: renderSkillMd(graph),
      [`${outputRoot}/module.yaml`]: renderModuleYaml(graph),
      [`${outputRoot}/module-help.csv`]: renderModuleHelpCsv(graph),
      [`${outputRoot}/review.md`]: renderReviewMd(graph),
    };
    for (const packet of BMAD_HANDOFF_PACKETS) {
      files[`${outputRoot}/${packet.path}`] = stringifyReviewPacket({
        boundary: 'Handoff/input packet only. Human operator chooses whether to run the referenced BMAD skill in a fresh context.',
        pack: graph.pack,
        skill: packet.skill,
        title: packet.title,
      });
    }

    for (const [relativePath, content] of Object.entries(files)) {
      const targetPath = resolveUnderRoot(config.project_root, relativePath, relativePath);
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      fs.writeFileSync(targetPath, content);
      await store.query(
        `
          UPDATE ${store.qualify('artifact_draft')}
          SET sha256 = $3, status = 'exported', generated_by_run_id = $4
          WHERE pack_draft_id = $1 AND relative_path = $2
        `,
        [graph.pack.id, relativePath, sha256(content), runId],
      );
    }
    await store.query(
      `
        INSERT INTO ${store.qualify('review_event')} (pack_draft_id, actor, event_type, comment_md)
        VALUES ($1, 'capability-forge', 'exported', 'BMAD handoff artifacts exported; no BMAD workflow was executed.')
      `,
      [graph.pack.id],
    );
    await store.finishRun(runId, 'succeeded', `exported ${slug}`);
    return {
      files: Object.keys(files).sort(),
      runId,
    };
  } catch (error) {
    await store.finishRun(runId, 'failed', error.message);
    throw error;
  }
}

function renderSkillMd({ capabilities, evidenceRefs, pack }) {
  return [
    '---',
    `name: ${pack.slug}`,
    `description: ${pack.description || pack.title}`,
    '---',
    '',
    `# ${pack.title}`,
    '',
    'Draft BMAD skill generated by Capability Pack Forge v2.',
    '',
    'This file is not installed and is not runtime authority until explicit promotion succeeds.',
    '',
    '## Capabilities',
    '',
    ...capabilities.map((capability) => `- ${capability.menu_code}: ${capability.title} - ${capability.intent}`),
    '',
    '## Evidence Refs',
    '',
    ...evidenceRefs.map((evidenceRef) => `- ${evidenceRef.ref} ${evidenceRef.uri}`),
    '',
  ].join('\n');
}

function renderModuleYaml({ pack }) {
  return [
    `code: ${pack.bmad_module_code}`,
    `name: ${pack.title}`,
    `description: ${pack.description || pack.title}`,
    `parent: ${pack.bmad_parent_module}`,
    'status: draft',
    'source: capability-pack-forge-v2',
    '',
  ].join('\n');
}

function renderModuleHelpCsv({ capabilities, pack }) {
  return [
    'module,skill,display-name,menu-code,description,action,args,phase,preceded-by,followed-by,required,output-location,outputs',
    ...capabilities.map((capability) =>
      [
        pack.bmad_module_code,
        pack.slug,
        capability.title,
        capability.menu_code,
        capability.intent.replaceAll('"', '""'),
        '',
        '',
        'anytime',
        '',
        '',
        'false',
        '{output_folder}/capability-packs',
        'capability pack artifacts',
      ]
        .map((value) => `"${String(value)}"`)
        .join(','),
    ),
    '',
  ].join('\n');
}

function renderReviewMd({ evidenceRefs, pack }) {
  return [
    `# Review: ${pack.title}`,
    '',
    '- Status: draft handoff',
    '- Boundary: Forge exported artifacts only; no BMAD workflow executed.',
    '- Promotion requires approved status and validation.',
    '',
    '## Evidence',
    '',
    ...evidenceRefs.map((evidenceRef) => `- ${evidenceRef.ref} ${evidenceRef.uri}`),
    '',
  ].join('\n');
}

module.exports = {
  exportBmadArtifacts,
  renderModuleHelpCsv,
  renderModuleYaml,
  renderSkillMd,
};
